### ISSUE TITLE
More explicite miss configuration error message

### ISSUE THREAD

**Issue by sanpii** [pomm-project/ModelManager#17]
Hello,

https://github.com/pomm-project/pomm-bundle/issues/18

The error message like:

> No pooler registered for type 'model'. Poolers available: {prepared_query, query_manager, converter, observer, inspector, listener}.
> Do you use the correct session builder?

And write (my eyes have skipped all text after …):

    $pomm = new Pomm([
        'project_name' => [
            'dsn' => …,
            'class:session_builder' => '\PommProject\ModelManager\SessionBuilder',
        ],
        …
    ]);

Is more readable.

**Comment by chanmix51** [comment]
Fixed in e743456

**Comment by stood** [comment]
https://github.com/pomm-project/Foundation/commit/e74345635745ed47504221e970afdc6be83f4c53
