### ISSUE TITLE
Empty primary key

### ISSUE THREAD

**Issue by tlode** [pomm-project/ModelManager#20]
If a `RowStructure` defines an empty primary key, like

```php
        $this
            ->setRelation('foo')
            ->setPrimaryKey([])
            ->addField('foo_id', 'int4')
            etc..
```

then `WriteQueries::updateOne` and `WriteQueries::deleteOne` build a query which will update or delete all rows! 

This is not a bug, but it should not be possible to define an empty primary key in a model.

The above code is the result of using the CLI code generator on a relation which uses a `UNIQUE` key instead of a `PRIMARY KEY`. Maybe the CLI code generator could throw a warning in such a case?

**Comment by chanmix51** [comment]
Even if it is good practice to define a primary key for each relation, I came across cases when there are none. In this case, it is still life saving to rely on Pomm and its ability to perform basic operations. 
Of course, methods like `updateOne()`, 'deleteByPk()` should throw an exception when primary key is empty.

Opinions welcome.

**Comment by stood** [comment]
https://github.com/pomm-project/ModelManager/pull/24
