### ISSUE TITLE
Is it possible to use transactions in functional tests?

### ISSUE THREAD

**Issue by v3106** [pomm-project/ModelManager#41]
I want to test a postAction method in a controller, ensure that new record was added. For example, if I'm using built-in `$this->model->createAndSave($data)` in the postAction and `$browser->request('POST', $url, $data)` in the testPostAction method, wrapping testPostAction in a transaction will not help because the query executes on the other connection. If I understand this correctly the only way is to copy the existing database on the setUp and drop the copy on the tearDown, which is rather slow so I will use it only if there are no more options.
Am I missing something and using transactions in this case is possible? And how do you test your controllers?

**Comment by chanmix51** [comment]
Ooops sorry, I forgot this issue. I am not sure I am getting your point. I do test controllers using stories. Model methods are unit tested appart with a small set of data.

**Comment by v3106** [comment]
I meant something like sharing pomm connection between the code in a controller and in a test to be able to wrap all the queries in a transaction. I'm using symfony and only recently have found that it is [possible](http://symfony.com/doc/current/book/testing.html#accessing-the-container) but not always reliable?

**Comment by chanmix51** [comment]
If I understand correctly, you want to execute a controller and test the changes in the database. Since your test queries are read-only, why do you want to wrap them in a transaction ?

**Comment by v3106** [comment]
I want queries in a controller (CRUD) to be wrapped in a transaction, not test queries. I don't have any direct queries in a test, only requests to the controller through the symfony's [client](http://symfony.com/doc/current/book/testing.html#working-with-the-test-client)

**Comment by v3106** [comment]
Here's a simplified example of what I mean:
```php
<?php

class ResourceController extends Controller
{
    public function postAction(Request $request)
    {
        $this->get('pomm.default_session')
             ->getModel('AppBundle\Schema\ResourceModel')
             ->createAndSave(json_decode($request->getContent(), true));
        return new Response(null, 201);
    }
}

class ResourceControllerTest extends WebTestCase
{
    private $client;
    private $pomm;

    public function setUp()
    {
        $this->client = static::createClient();
        // get internal pomm session
        $this->pomm = $this->client->getContainer()
                                   ->get('pomm.default_session');
        $this->pomm->getConnection()
                   ->executeAnonymousQuery('begin');
    }

    public function tearDown()
    {
        $this->pomm->getConnection()
                   ->executeAnonymousQuery('rollback');
    }

    public function test_post()
    {
        $this->client->request('POST', 'api/resource', [], [], [],
            json_encode(['key' => 'value'])
        );
        self::assertEquals(201, $this->client->getResponse()->getStatusCode());
    }
}
```
Will I have any problems with this in the future?

**Comment by chanmix51** [comment]
I think yes. You might want to have a test basis transaction instead of all the tests in a transaction. If you want to test a database failure, the whole transaction will be blocked until rollback despite the test being OK.

**Comment by v3106** [comment]
Thanks, good point. There are also savepoints in PostgreSQL which can be useful in this case.

**Comment by chanmix51** [comment]
Can we close that issue ?
