### ISSUE TITLE
Projection::unsetFields() to unset several fields at once

### ISSUE THREAD

**Issue by chanmix51** [pomm-project/ModelManager#48]
It would be nice to be able to unset several fields at once from a Projection:

```
$this->createProjection()->unsetFields(['field_1', 'field_2', …, 'field_N']);
```

Any thoughts ?

**Comment by tlode** [comment]
Good for some kind of dynamic approach. +1

Nevertheless, since `unsetField` returns `$this`, I would prefer calling it multiple times.

**Comment by chanmix51** [comment]
That's true, the main goal of this method would be to keep the code compact yet readable.

**Comment by stood** [comment]
It's good for this issue plz closed :)
