### ISSUE TITLE
Disable Prefixing with session name and/or schema

### ISSUE THREAD

**Issue by mvrhov** [pomm-project/ModelManager#60]
If only one schema and/or session is used in a project then there is no need to nest the Models so deep.

Having an option to disable prefix for either of them would be nice as this would also mean less deep namespaces

**Comment by chanmix51** [comment]
IMHO, the good way of doing the thing is the way it is done in Pomm 1.x. Giving the user to specify the path as a pattern like `--dir-pattern={Session}/{Schema}Schema` or, in your case `--dir-pattern={Session}` but it could also accept constant expressions like `--dir-pattern=Database/{Session}Production/{Schema}Schema`

Would that be ok ?

**Comment by mvrhov** [comment]
That would be ok

**Comment by chanmix51** [comment]
Fixed with Pomm-Project/Cli#31
