### ISSUE TITLE
Choose not to return the projection of the query

### ISSUE THREAD

**Issue by monpetitjules** [pomm-project/ModelManager#76]
For security reasons I want to query a table with a Postgresql role that has only insert permission (the user is not the owner of the table). 

As every Pomm WriteQueries returns the projection, I get the following error message:
ERROR:  permission denied for relation table.

The role must also have "select" permission to return the projection.

Would it be possible to choose not to return the projection of queries (it could just return true or false instead) in order to use a role without select permission?

Thanks.

**Comment by chanmix51** [comment]
You do not want to use the model manager for those queries do you? Do you think an entity should be hydrated with the query result? IMHO, the `QueryManager` should be fine.

**Comment by chanmix51** [comment]
Can we close this issue?
